### PR TITLE
Basic Support for iOS 8/7

### PR DESCRIPTION
**Pull request by brendonjkding**
Tested on 14.3, 12.4, 8.4.1, 7.1.2.

### CODE REVIEW

**Comment by opa334** [comment]
Hey, thanks for the PR!

Can you refactor it to use a class extension (e.g. add new methods with an atl_ prefix that implement the missing functionality if needed and call the stock method when it's available)? Because I don't think adding them with %new is a good idea, I want to avoid that.

Also my main reason for not support iOS 8 and down is because IIRC dynamic libraries have to be compiled with Xcode 9 to work on such low versions, is that not the case?

**Comment by brendonjkding** [comment]
Thanks for your advice. I'll refactor it soon. 
I compiled with Xcode 11 and it works fine. It seems iOS 7 is the lowest supported version if we don't use Xcode 9.

**Comment by brendonjkding** [comment]
Hi. I have refactored it as advised. Please have a look.

**Comment by opa334** [comment]
thanks, will merge this soon

**Pull request merged**
